### ISSUE TITLE
Switch to more standard bitcore-message

### ISSUE THREAD

**Issue by harlantwood** [digitalbazaar/jsonld-signatures#18] opened 2016-12-06 05:57 UTC
Currently we have in our dependencies:

```
    "bitcore-message": "github:CoMakery/bitcore-message#dist",
```

https://github.com/digitalbazaar/jsonld-signatures/blob/d2c96175d24c673ea6fbd25bb34b4e5a453b07c7/package.json#L37

This was necessary to get a browser bundle which gave us access to Bitcore as well as BitcoreMessage.  Including both does not work, by design.  

Solution: create a PR in their repo, and use that version instead.

**Comment by hidde-jan** [comment] 2017-10-25 12:15
This is an old issue, but it's still open and having a custom dependency that hasn't been updated since 2015 doesn't seem like a good idea.

**Comment by harlantwood** [comment] 2017-10-25 20:27
@hidde-jan I largely agree.  Would you like to see if bitcore has updated their code so this workaround is no longer needed, or if it is still needed, look into creating a PR in their repo?

**Comment by hidde-jan** [comment] 2017-10-25 21:10
Sure. I understand the problem is in the web distribution of the json-ld
signatures package? On node I don't see a reason for using the special
branch.

Op 25 okt. 2017 10:27 p.m. schreef "Harlan T Wood" <notifications@github.com

**Comment by hidde-jan** [comment] 2017-12-01 11:16
@harlantwood I've taken a look, and while I'm not completely familiar with phantomjs, it seems the problem is not really in bitcore-messages, but in the way the phantomjs tests are currently written. The tests import bitcore-messages directly from node_modules, but bitcore-messages needs to be compiles/browserified first before it can be used.

To me, this seems to be more of a problem of how the testing is performed instead of something that needs to be addressed on the bitcore-messages side of things.

**Comment by harlantwood** [comment] 2017-12-01 19:48
@hidde-jan I agree that the test setup is non standard and likely suboptimal.  

Even if we did the browserification in the test setup, this is the commit we would be missing: https://github.com/CoMakery/bitcore-message/commit/cf708ba8405a8fee2367f61f06cb3804cf9cb5d9

**Comment by harlantwood** [comment] 2017-12-01 21:25
So when I suggested 

> Solution: create a PR in their repo, and use that version instead.

That is the commit in question, though we should check first if they have already some something like this.

**Comment by dlongley** [comment] 2021-07-11 21:32
This is no longer applicable, closing.

**Closed by dlongley** 2021-07-11 21:32 UTC
